{% set name = "ubermagtable" %}
{% set version = "0.61.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('_', '-') }}-{{ version }}.tar.gz
  sha256: 14743f266a83f52d6e5de2ff19c8528bd6c069aaa4c2145f1bcf5f2dfdb8aaa3

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - ubermagutil >=0.62.0
    - matplotlib-base >=3.3
    - jupyterlab >=3.0,<4.0
    - pandas >=1.1
    - ipywidgets

test:
  imports:
    - ubermagtable
  commands:
    - python -c "import sys; import ubermagtable; sys.exit(ubermagtable.test())"

about:
  home: http://ubermag.github.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python package for manipulating tabular data.
  doc_url: https://ubermag.github.io/documentation/ubermagtable.html
  dev_url: https://github.com/ubermag/ubermagtable

extra:
  recipe-maintainers:
    - marijanbeg
    - fangohr
    - lang-m
    - samjrholt
    - swapneelap
