{% set name = "ubermagtable" %}
{% set version = "0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c54786bc74a45661cf90c5e2dcfa1c9013f065b2d23a750a9c842424b39256b5

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - ubermagutil ==0.2.7
    - pandas >=1.2
    - matplotlib-base >=3.3
    - jupyterlab ==2.2
    - ipywidgets >=7.6

test:
  imports:
    - ubermagtable
  commands:
    - python -c "import sys; import ubermagtable; sys.exit(ubermagtable.test())"

about:
  home: http://ubermag.github.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python package for manipulating tabular data.
  doc_url: http://ubermagtable.readthedocs.io
  dev_url: https://github.com/ubermag/ubermagtable

extra:
  recipe-maintainers:
    - marijanbeg
    - fangohr
    - lang-m
