{% set version = "0.1.4" %}
{% set name = "ubermagtable" %}
{% set sha256 = "d05b0d84f5f4d824c48276aa8530fbeba4e528cd98715028586d6605f4e2a3ba" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: pip install --no-deps . -vvv

requirements:
  build:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pandas
    - numpy
    - pytest

test:
  imports:
    - ubermagtable
  commands:
    - python -c "import sys; import ubermagtable as ut; sys.exit(ut.test())"

about:
  home: http://ubermag.github.io/
  license: BSD-3-clause
  license_family: BSD
  license_file: LICENSE
  summary: Reading and merging of OOMMF .odt and mumax3 .txt files
  doc_url: http://ubermagtable.readthedocs.io
  dev_url: https://github.com/ubermag/ubermagtable

  description: |
    `ubermagtable` is a Python package that provides:

    - Conversion of scalar data files (OOMMF `.odt` and mumax3 `.txt`) to `pandas.DataFrames`
    - Merging of multiple OOMMF `.odt` files into a single `pandas.DataFrame`

    It is available on all major operating systems (Windows, MacOS, Linux) and requires Python 3.6 or higher.

extra:
  recipe-maintainers:
    - marijanbeg
