{% set name = "ubermagtable" %}
{% set version = "0.61.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('_', '-') }}-{{ version }}.tar.gz
  sha256: 64c8b860dd33ecdcdec23692b39befa30727518cde6588d8be34304ff6df249c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - ubermagutil >=0.63.2
    - matplotlib-base >=3.3
    - pandas >=1.1
    - ipywidgets >=7.5

test:
  imports:
    - ubermagtable
  commands:
    - python -c "import sys; import ubermagtable; sys.exit(ubermagtable.test())"

about:
  home: http://ubermag.github.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python package for manipulating tabular data.
  doc_url: https://ubermag.github.io/documentation/ubermagtable.html
  dev_url: https://github.com/ubermag/ubermagtable

extra:
  recipe-maintainers:
    - marijanbeg
    - fangohr
    - lang-m
    - samjrholt
    - swapneelap
