{% set name = "ubermagtable" %}
{% set version = "0.60.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 367b6b0d7611c5d661c06ce9ad658765b0dcd0edb306751593b8dfdc6a688870

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - ubermagutil >=0.60.0,<0.61.0
    - matplotlib-base >=3.3
    - jupyterlab >=3.0,<4.0
    - pandas >=1.1
    - ipywidgets

test:
  imports:
    - ubermagtable
  commands:
    - python -c "import sys; import ubermagtable; sys.exit(ubermagtable.test())"

about:
  home: http://ubermag.github.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python package for manipulating tabular data.
  doc_url: https://ubermag.github.io/documentation/ubermagtable.html
  dev_url: https://github.com/ubermag/ubermagtable

extra:
  recipe-maintainers:
    - marijanbeg
    - fangohr
    - lang-m
    - samjrholt
