{% set name = "ubermagtable" %}
{% set version = "0.62.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('_', '-') }}-{{ version }}.tar.gz
  sha256: 531c711b466f8bf7a1fda634c2f92a6ec19599e1680501662c2106caccaeea98

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - ubermagutil >=0.64.0
    - matplotlib-base >=3.3
    - pandas >=1.1
    - ipywidgets >=7.5

test:
  requires:
    - python {{ python_min }}
  imports:
    - ubermagtable
  commands:
    - python -c "import sys; import ubermagtable; sys.exit(ubermagtable.test())"

about:
  home: http://ubermag.github.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python package for manipulating tabular data.
  doc_url: https://ubermag.github.io/documentation/ubermagtable.html
  dev_url: https://github.com/ubermag/ubermagtable

extra:
  recipe-maintainers:
    - marijanbeg
    - fangohr
    - lang-m
    - samjrholt
    - swapneelap
