{% set name = "ubermagtable" %}
{% set version = "0.1.9" %}
{% set sha256 = "a03b3a73e7f102adbb2356f77d2bafbd88d7110aa868afbb532f05ab89f6c3a8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pandas
    - numpy
    - pytest

test:
  imports:
    - ubermagtable
  commands:
    - python -c "import sys; import ubermagtable as ut; sys.exit(ut.test())"

about:
  home: http://ubermag.github.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python package for manipulating tabular data.
  doc_url: http://ubermagtable.readthedocs.io
  dev_url: https://github.com/ubermag/ubermagtable

extra:
  recipe-maintainers:
    - marijanbeg
    - fangohr
