{% set name = "ubermagtable" %}
{% set version = "0.1.7" %}
{% set sha256 = "7a830ee74ed3e00f5e1e74da65a89beae22c0efab0bbb42b11a0958fcf8c1ead" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pandas
    - numpy
    - pytest

test:
  imports:
    - ubermagtable
  commands:
    - python -c "import sys; import ubermagtable as ut; sys.exit(ut.test())"

about:
  home: http://ubermag.github.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Python package for manipulating tabular data.'
  doc_url: http://ubermagtable.readthedocs.io
  dev_url: https://github.com/ubermag/ubermagtable

extra:
  recipe-maintainers:
    - marijanbeg
    - fangohr
