{% set name = "ubermagtable" %}
{% set version = "0.1.11" %}
{% set sha256 = "aa68c8e7abcf25a6c27429f780f87045bdae9b675798dd7d9ff72ab4acc5a4af" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - ubermagutil ==0.2.6
    - pandas >=1.0
    - matplotlib-base >=3.2
    - jupyterlab >=2.1
    - ipywidgets >=7.5

test:
  imports:
    - ubermagtable
  commands:
    - python -c "import sys; import ubermagtable as ut; sys.exit(ut.test())"

about:
  home: http://ubermag.github.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python package for manipulating OOMMF and mumax3 tabular data.
  doc_url: http://ubermagtable.readthedocs.io
  dev_url: https://github.com/ubermag/ubermagtable

extra:
  recipe-maintainers:
    - marijanbeg
    - fangohr
