travis:
  secure:
    BINSTAR_TOKEN: qjvYky1Z1PBZgZqB5kEUmEVRsNu9BMkaYpSu2hi5L1fZ3jzS8+CdizKANkiJzYEQIjX3vaJZM42ZdUm3pfGAT9wQDjZy2Xk7kSUhqmtPPCqtTlSTYlvMEKMbUeGvi8uf5Zo7WVVL0RS9BE0VzPxsEFp+LPlYsD+MEjnYxhwTokyMNu5Mhge1yVu6avYnOwO8FbBhYvNWDxgqiZSACgCXiYRVOiP5DlD3ZBt7drtokVDDHlPmNPDdfuxl+3RfC8oPamMmrvVgKCUs8ewtO/kPxKrJaTAS0xTipfVHH7kpUBdURKBOgX9GU82iEmnVneNPwT4/1WmWAoGqbg10DeJk0sExO5jg8ZYTb4vnGEjk6xQH6KyzCXNWAZLDscR+jD65vLsq0N4by3bHXJ2t70wAyLqDVgwh+0S432cJaWNdvLNS6vhOzyTA2GcOaR0BcdAfRvgBo2pX71uqD0ZEa+/3Ma9NdVWBT3lTxL/vN24U/vW96i0xJY7PUPhSrddPCJIdHZbDRR1f/vWGUuxWg1YrT0uRVYRJWtEnlNd+EvKb3Mi6W+7/vCQKpfpicblJylspBjAg9C96WruvGQbYOOC19qKEaOJdqNiBtDsC0eQ5fg8TVV7lKTIfD0QUN6IgxEJ9t+c+Wjd6jiWAcKIer8CGqj42c0B38AKjv3UKKeRu71Q=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
